INSERT INTO ACADEMIC_HISTORY VALUES ('1', '1', '15', 'graduado', 'regular', 'consequat');
INSERT INTO ACADEMIC_HISTORY VALUES ('2', '2', '5', 'activo', 'regular', NULL);
INSERT INTO ACADEMIC_HISTORY VALUES ('3', '3', '6', 'activo', 'regular', NULL);
INSERT INTO ACADEMIC_HISTORY VALUES ('4', '4', '13', 'graduado', 'regular', 'quis justo maecenas rhoncus');
INSERT INTO ACADEMIC_HISTORY VALUES ('5', '5', '13', 'en pausa', 'regular', NULL);
INSERT INTO ACADEMIC_HISTORY VALUES ('6', '6', '5', 'graduado', 'regular', 'curabitur gravida nisi at');
INSERT INTO ACADEMIC_HISTORY VALUES ('7', '7', '10', 'activo', 'regular', NULL);
INSERT INTO ACADEMIC_HISTORY VALUES ('8', '8', '1', 'activo', 'admisión con nivelación', NULL);
INSERT INTO ACADEMIC_HISTORY VALUES ('9', '9', '18', 'graduado', 'regular', 'nisl');
INSERT INTO ACADEMIC_HISTORY VALUES ('10', '10', '16', 'retirado', 'regular', NULL);
INSERT INTO ACADEMIC_HISTORY VALUES ('11', '11', '11', 'activo', 'regular', NULL);
INSERT INTO ACADEMIC_HISTORY VALUES ('12', '12', '14', 'activo', 'regular', NULL);
INSERT INTO ACADEMIC_HISTORY VALUES ('13', '13', '18', 'graduado', 'regular', 'nisl');
INSERT INTO ACADEMIC_HISTORY VALUES ('14', '14', '7', 'activo', 'admisión con nivelación', NULL);
INSERT INTO ACADEMIC_HISTORY VALUES ('15', '15', '14', 'graduado', 'regular', 'donec posuere');
INSERT INTO ACADEMIC_HISTORY VALUES ('16', '16', '3', 'activo', 'regular', NULL);
INSERT INTO ACADEMIC_HISTORY VALUES ('17', '17', '3', 'activo', 'regular', NULL);
INSERT INTO ACADEMIC_HISTORY VALUES ('18', '18', '14', 'en pausa', 'programas especiales', NULL);
INSERT INTO ACADEMIC_HISTORY VALUES ('19', '19', '4', 'activo', 'admisión con nivelación', NULL);
INSERT INTO ACADEMIC_HISTORY VALUES ('20', '20', '2', 'activo', 'regular', NULL);
