INSERT INTO CLASSROOM VALUES ('1', '187', 'magna vestibulum', '5');
INSERT INTO CLASSROOM VALUES ('2', '342', NULL, '3');
INSERT INTO CLASSROOM VALUES ('3', '378', 'lacus morbi quis tortor', '4');
INSERT INTO CLASSROOM VALUES ('4', '145', 'iaculis justo in', '3');
INSERT INTO CLASSROOM VALUES ('5', '404', 'faucibus', '1');
INSERT INTO CLASSROOM VALUES ('6', '469', NULL, '1');
INSERT INTO CLASSROOM VALUES ('7', '387', NULL, '4');
INSERT INTO CLASSROOM VALUES ('8', '481', NULL, '1');
INSERT INTO CLASSROOM VALUES ('9', '224', 'dolor morbi', '5');
INSERT INTO CLASSROOM VALUES ('10', '237', 'suspendisse accumsan', '4');
INSERT INTO CLASSROOM VALUES ('11', '222', NULL, '1');
INSERT INTO CLASSROOM VALUES ('12', '251', NULL, '5');
INSERT INTO CLASSROOM VALUES ('13', '400', 'purus eu magna vulputate', '1');
INSERT INTO CLASSROOM VALUES ('14', '122', NULL, '4');
INSERT INTO CLASSROOM VALUES ('15', '463', 'accumsan tortor quis', '1');
INSERT INTO CLASSROOM VALUES ('16', '403', 'convallis eget eleifend', '4');
INSERT INTO CLASSROOM VALUES ('17', '322', 'sagittis sapien', '1');
INSERT INTO CLASSROOM VALUES ('18', '492', 'lectus pellentesque at nulla suspendisse', '1');
INSERT INTO CLASSROOM VALUES ('19', '220', NULL, '3');
INSERT INTO CLASSROOM VALUES ('20', '170', 'elementum eu interdum eu tincidunt', '2');
