INSERT INTO PROGRAM VALUES ('1', 'pretium iaculis justo', '4', 'maestría');
INSERT INTO PROGRAM VALUES ('2', 'metus sapien ut nunc', '5', 'pregrado');
INSERT INTO PROGRAM VALUES ('3', 'id', '14', 'pregrado');
INSERT INTO PROGRAM VALUES ('4', 'in', '13', 'pregrado');
INSERT INTO PROGRAM VALUES ('5', 'curabitur gravida nisi at', '20', 'educación continua');
INSERT INTO PROGRAM VALUES ('6', 'vestibulum ante', '10', 'maestría');
INSERT INTO PROGRAM VALUES ('7', 'tristique in', '2', 'pregrado');
INSERT INTO PROGRAM VALUES ('8', 'cubilia', '14', 'pregrado');
INSERT INTO PROGRAM VALUES ('9', 'sapien', '20', 'especialización');
INSERT INTO PROGRAM VALUES ('10', 'aenean auctor gravida', '19', 'pregrado');
INSERT INTO PROGRAM VALUES ('11', 'nibh in lectus pellentesque', '16', 'educación continua');
INSERT INTO PROGRAM VALUES ('12', 'lorem', '9', 'educación continua');
INSERT INTO PROGRAM VALUES ('13', 'quis justo maecenas rhoncus', '1', 'especialización');
INSERT INTO PROGRAM VALUES ('14', 'donec posuere', '18', 'maestría');
INSERT INTO PROGRAM VALUES ('15', 'consequat', '2', 'pregrado');
INSERT INTO PROGRAM VALUES ('16', 'vestibulum eget', '8', 'doctorado');
INSERT INTO PROGRAM VALUES ('17', 'vestibulum ante ipsum primis', '19', 'pregrado');
INSERT INTO PROGRAM VALUES ('18', 'nisl', '9', 'pregrado');
INSERT INTO PROGRAM VALUES ('19', 'sit amet nulla quisque', '7', 'especialización');
INSERT INTO PROGRAM VALUES ('20', 'in hac habitasse platea', '6', 'pregrado');
