INSERT INTO SUBJECT VALUES ('1', 'quam', '5', '4');
INSERT INTO SUBJECT VALUES ('2', 'erat quisque erat eros', '3', '4');
INSERT INTO SUBJECT VALUES ('3', 'diam in magna bibendum', '11', '4');
INSERT INTO SUBJECT VALUES ('4', 'donec quis', '16', '4');
INSERT INTO SUBJECT VALUES ('5', 'platea dictumst', '20', '3');
INSERT INTO SUBJECT VALUES ('6', 'lectus', '8', '3');
INSERT INTO SUBJECT VALUES ('7', 'nulla tellus in', '13', '4');
INSERT INTO SUBJECT VALUES ('8', 'eleifend luctus', '12', '4');
INSERT INTO SUBJECT VALUES ('9', 'nulla ultrices', '3', '4');
INSERT INTO SUBJECT VALUES ('10', 'nisl venenatis lacinia aenean', '18', '4');
INSERT INTO SUBJECT VALUES ('11', 'tristique tortor', '11', '5');
INSERT INTO SUBJECT VALUES ('12', 'interdum in ante', '19', '3');
INSERT INTO SUBJECT VALUES ('13', 'massa', '18', '4');
INSERT INTO SUBJECT VALUES ('14', 'scelerisque quam turpis', '11', '4');
INSERT INTO SUBJECT VALUES ('15', 'vestibulum sagittis sapien cum', '3', '4');
INSERT INTO SUBJECT VALUES ('16', 'cubilia curae mauris viverra', '6', '3');
INSERT INTO SUBJECT VALUES ('17', 'turpis eget', '11', '4');
INSERT INTO SUBJECT VALUES ('18', 'pellentesque viverra pede ac', '7', '5');
INSERT INTO SUBJECT VALUES ('19', 'nisi volutpat', '14', '2');
INSERT INTO SUBJECT VALUES ('20', 'aenean', '4', '4');
INSERT INTO SUBJECT VALUES ('21', 'nibh in quis justo', '2', '4');
INSERT INTO SUBJECT VALUES ('22', 'at turpis a pede', '6', '4');
INSERT INTO SUBJECT VALUES ('23', 'nibh fusce lacus purus', '3', '4');
INSERT INTO SUBJECT VALUES ('24', 'sem fusce consequat', '10', '2');
INSERT INTO SUBJECT VALUES ('25', 'pede', '11', '4');
INSERT INTO SUBJECT VALUES ('26', 'vehicula consequat morbi', '5', '3');
INSERT INTO SUBJECT VALUES ('27', 'sapien varius', '6', '4');
INSERT INTO SUBJECT VALUES ('28', 'massa', '7', '4');
INSERT INTO SUBJECT VALUES ('29', 'erat tortor sollicitudin', '1', '4');
INSERT INTO SUBJECT VALUES ('30', 'libero quis orci', '4', '4');
INSERT INTO SUBJECT VALUES ('31', 'habitasse platea dictumst', '13', '2');
INSERT INTO SUBJECT VALUES ('32', 'justo sollicitudin ut suscipit', '19', '4');
INSERT INTO SUBJECT VALUES ('33', 'bibendum imperdiet nullam', '20', '4');
INSERT INTO SUBJECT VALUES ('34', 'sapien', '16', '2');
INSERT INTO SUBJECT VALUES ('35', 'suspendisse potenti cras in', '16', '3');
INSERT INTO SUBJECT VALUES ('36', 'vel nisl duis ac', '9', '4');
INSERT INTO SUBJECT VALUES ('37', 'libero', '8', '4');
INSERT INTO SUBJECT VALUES ('38', 'ac', '19', '4');
INSERT INTO SUBJECT VALUES ('39', 'quisque arcu libero', '5', '3');
INSERT INTO SUBJECT VALUES ('40', 'urna', '15', '4');
INSERT INTO SUBJECT VALUES ('41', 'non', '1', '4');
INSERT INTO SUBJECT VALUES ('42', 'consectetuer adipiscing', '7', '4');
INSERT INTO SUBJECT VALUES ('43', 'luctus rutrum nulla tellus', '11', '2');
INSERT INTO SUBJECT VALUES ('44', 'vulputate', '13', '3');
INSERT INTO SUBJECT VALUES ('45', 'sit amet nulla', '9', '4');
INSERT INTO SUBJECT VALUES ('46', 'aliquam quis', '2', '4');
INSERT INTO SUBJECT VALUES ('47', 'integer', '4', '4');
INSERT INTO SUBJECT VALUES ('48', 'purus', '14', '3');
INSERT INTO SUBJECT VALUES ('49', 'ut', '17', '2');
INSERT INTO SUBJECT VALUES ('50', 'vestibulum quam sapien', '16', '3');
